#92 and some more
rutor/PA165-projekt pull request #105
Opened 2019-01-10 23:30 UTC by xtrnkal

2019-01-11 00:05 UTC, rutor commented on web/src/main/webapp/WEB-INF/jsp/home.jsp
> -                    <my:a href="show/${show.id}">
show is correct path

2019-01-11 00:07 UTC, rutor requested changes
/show_detail/* is not mapped in controller

2019-01-13 22:26 UTC, xtrnkal commented on web/src/main/webapp/WEB-INF/jsp/home.jsp
> -                    <my:a href="show/${show.id}">
show_detail is correct path

2019-01-13 22:56 UTC, rutor commented on web/src/main/java/cz/muni/fi/pa165/mvc/controllers/HomeController.java
> +    @RequestMapping(value = "/show_detail/{id}", method = RequestMethod.POST)
Proc `/show_detail/id` vyzaduje CreateBookingDTO?

2019-01-13 22:56 UTC, rutor commented on web/src/main/java/cz/muni/fi/pa165/mvc/controllers/HomeController.java
> +        Long idBook = bookingFacade.create(dto);
Proc `/show_detail` neco vytvari?

2019-01-13 22:58 UTC, rutor commented on web/src/main/java/cz/muni/fi/pa165/mvc/controllers/HomeController.java
> +    @RequestMapping(value = "/bookings_tickets/{id}", method = RequestMethod.GET)
ID v adrese je bezpecnostni riziko. V session je ulozeny autorizovany uzivatel, tak id vytahni z toho objektu

2019-01-13 23:01 UTC, rutor submitted a review, later dismissed

2019-01-13 23:04 UTC, xtrnkal commented on web/src/main/java/cz/muni/fi/pa165/mvc/controllers/HomeController.java
> +    @RequestMapping(value = "/show_detail/{id}", method = RequestMethod.POST)
old code, removed

2019-01-13 23:04 UTC, xtrnkal commented on web/src/main/java/cz/muni/fi/pa165/mvc/controllers/HomeController.java
> +        Long idBook = bookingFacade.create(dto);
old code, removed

2019-01-13 23:04 UTC, xtrnkal commented on web/src/main/java/cz/muni/fi/pa165/mvc/controllers/HomeController.java
> +    @RequestMapping(value = "/bookings_tickets/{id}", method = RequestMethod.GET)
old code, removed

2019-01-13 23:05 UTC, rutor approved these changes
OK

2019-01-13 23:32 UTC, merged