Milestone3/tr rest module creation
rutor/PA165-projekt pull request #69
Opened 2018-12-14 01:08 UTC by rutor

2018-12-14 08:39 UTC, tyrylu requested changes
Skoro, ale ten controller by chtělo pročistit/pojmenovat správně. Jinak, .gitignore v podadresářích se obecně nedoporučujou a stejně git začíná kontrolou toho v rootu (viz. git check-ignore -v some.class v jakýmkoliv podadresáři), takže ty ignorovaný vzory kdyžtak přidat tam, resp. ho v top level .gitignore opravit.

2018-12-14 08:39 UTC, tyrylu commented on rest/src/main/java/cz/muni/fi/pa165/RootWebContext.java
> +        //registry.addInterceptor(new AllowOriginInterceptor());
Už možná otravná věc - buď tam ten interceptor bude, nebo bych ten řádek dal pryč jako takovej. :-)

2018-12-14 08:39 UTC, tyrylu commented on rest/src/main/java/cz/muni/fi/pa165/RootWebContext.java
> +        //objectMapper.addMixIn(ProductDTO.class, ProductDTOMixin.class);
Pryč s ním.

2018-12-15 15:39 UTC, xtrnkal approved these changes
seems ok

2018-12-15 15:59 UTC, tyrylu approved these changes
To už vypadá ok.

2018-12-15 16:00 UTC, merged